### PR TITLE
[nic] add an additional explanation (Backport To Stable-1.3)

### PR DESCRIPTION
**Pull request by hmeAtos**
Hi guys,

I added some explanations on the VLAN which were not clear to some users.

Regards,
Hamid

### CODE REVIEW

**Comment by btravouillon** [comment]
This still applies to nic role in master. Can you open a PR for master first, then backport it?

**Comment by hmeAtos** [comment]
> This still applies to nic role in master. Can you open a PR for master first, then backport it?

of course

**Review by oxedions — APPROVED** [review]
Dear @hmeAtos 

Thanks a lot for this backport 😊 

Merging.

**Comment by hmeAtos** [comment]
> Dear @hmeAtos
> 
> Thanks a lot for this backport 😊
> 
> Please tell me once not a draft so I can merge, but right now it is ok for me.

it's good @oxedions

**Pull request merged**
