### PR TITLE
Fix: powerman - Allow bigger configurations

### PR DESCRIPTION
**Pull request by oxedions**
Credits goes to @btravouillon

From https://github.com/bluebanquise/bluebanquise/pull/549

### CODE REVIEW

**Comment by btravouillon** [comment]
Yeah :-)

**Comment by oxedions** [comment]
Hey !! :grinning:
Hello @btravouillon !
Sorry for being so slow to do this PR :innocent:

**Review by btravouillon — APPROVED** [review]
Looks good to me. 👍

**Comment by oxedions** [comment]
Thanks a lot !!! 😊

**Pull request merged**
