### PR TITLE
feat: add role core/firewall

### PR DESCRIPTION
**Pull request by actatux**
Read the readme first. :-)

Add new role core/firewall. Only support RHEL/CentOS.
This role should integrate seamlessly with the firewalld tasks in the core roles.

### CODE REVIEW

**Comment by oxedions** [comment]
Dear @actatux 

Thanks for this new role 😊 

In case it impacts your devs, please note that I will very probably introduce a breaking change very soon.

Current:

```
          network_interfaces:
            enp0s3:
              ip4: 10.10.0.1
              mac: 08:00:27:dc:f8:f5
              network: ice1-1
            ib0:
              ip4: 10.20.0.1
              network: interconnect-1
```

Will become:

```
          network_interfaces:
            - interface: enp0s3
              ip4: 10.10.0.1
              mac: 08:00:27:dc:f8:f5
              network: ice1-1
            - interface: ib0
              ip4: 10.20.0.1
              network: interconnect-1
```

With the following rules:

1. First item in the list is the hosts main resolution network (here, c001 for example will be on the same line than c001-ice1-1 in the hosts file).
2. First management network related item in the list will be the ansible mains ssh target interface (from ssh_master role), and also the main management network interface for the client (services_ip to target on client side).

If I wish direct resolution to be on interconnect-1 here, I simply move it first in the list. Ansible ssh will still use ice1-1 network, but ping c001 will be through interconnect-1.

This change provides:

* Greater powers to system administrator, as now, choice of main resolution **and** main management interface between each network is available.
* Removal of the need of global_network, i.e. simplification for hosts_file and dns_server.
* Simpler nic role, with better integration with Ansible nmcli module.
* Full removal of all j2_variables, massive code simplification.

**Comment by actatux** [comment]
New version with new network_interfaces data structure.
Move the role from addon to core as discussed with @oxedions.

**Comment by oxedions** [comment]
Ok nice. New network interfaces are now in master.

**Comment by actatux** [comment]
The role is ready, I still have to implement the verify part of molecule tests.

**Comment by oxedions** [comment]
Dear @actatux 

Very nice role ! I was going to ask for masquerading, and found you already added it.

I will review it this weekend, to have time to read all.

**Pull request merged**
