### PR TITLE
Add new role audit_system to configure properly audit logs in RHEL8/centos8

### PR DESCRIPTION
**Pull request by osmocl**
* Default auditd configuration is suitable for RHEL8/Centos8 systems
* allows to send audit logs to the syslog server
* adding some molecule tests

@thiagocardozo @ginomcevoy I was not able to add you as reviewers. 
Please take a look at this PR, this new role need to be used in SMC too.

### CODE REVIEW

**Comment by oxedions** [comment]
Dear @osmocl 

Thanks a lot for these modifications. I will test the role and come back to you as soon as possible 🙂

**Comment by oxedions** [comment]
Dear @osmocl 

The auditd service cannot be that easily manipulated:

image

Basically, you cannot restart auditd with `systemctl` command. Only known workaround is to use `service` command instead.
https://sleeplessbeastie.eu/2020/05/01/how-to-temporarily-stop-auditd-daemon/
However, this is a workaround, and I do not know if this will work on every distributions. This part needs to be studied.

Also, since auditd can send sensitive data, I think that task "Allow audit logs to be forwarded to remote syslog server" should be triggered only if a variable (I let you choose the name 😊 ) is set to true, and that is false by default.

1.5.0 is scheduled for end of November if all goes well, you have time 🙂

**Comment by osmocl** [comment]
> Dear @osmocl
> 
> The auditd service cannot be that easily manipulated:
> 
> image
> 
> Basically, you cannot restart auditd with `systemctl` command. Only known workaround is to use `service` command instead. https://sleeplessbeastie.eu/2020/05/01/how-to-temporarily-stop-auditd-daemon/ However, this is a workaround, and I do not know if this will work on every distributions. This part needs to be studied.
> 
> Also, since auditd can send sensitive data, I think that task "Allow audit logs to be forwarded to remote syslog server" should be triggered only if a variable (I let you choose the name 😊 ) is set to true, and that is false by default.
> 
> 1.5.0 is scheduled for end of November if all goes well, you have time 🙂


Hello @oxedions,

I found out a better way to manage the auditd service, we would need to use the FQCN service module.
The role was tested OK in the below VMs:

* Red Hat Enterprise Linux 8.4 (ansible 2.9.23 + python 3.6.8)
* CentOS Stream 8 (ansible 2.9.27 + python 3.6.8)
* Ubuntu 20.04.3 LTS (ansible 2.9.6 + python 3.8.10)
* Ubuntu 18.04.6 LTS (ansible 2.9.27 + python 2.7.17)

Please let me know it you think the role is OK 🙂

**Comment by oxedions** [comment]
Dear @osmocl 

Thanks a lot. I tested it and it worked also on my side.

I would ask one last thing: could you update variable `forward_audit_logs` name to `audit_system_forward_audit_logs`, as each variable must be prefixed by role name.

Then it is ok for me. 🙂

**Comment by osmocl** [comment]
> I would ask one last thing: could you update variable `forward_audit_logs` name to `audit_system_forward_audit_logs`, as each variable must be prefixed by role name.

Hello @oxedions,
Done !
Thanks

**Comment by oxedions** [comment]
Thanks a lot !

This is ok for me now. Thank you for this contribution to the CORE. 😊 

Merging.

**Pull request merged**
