### PR TITLE
Feat: conman - Add #639 related feature

### PR DESCRIPTION
**Pull request by johnnykeats**
Add support for external BMC
Add support for advanced credentials

### CODE REVIEW

**Comment by oxedions** [comment]
Beware, this template has no checks, so it will fail if something is not coherent in the inventory.
It may be on purpose...

**Comment by ginomcevoy** [comment]
Hello @johnnykeats , thanks for this PR.
I tested this, and the fallback is working well. Using the "traditional" inventory produces the same result.

However, when using the extended data model it does not work. If I am understanding correctly, the template tries to use the "ep_host_authentication" from the node,  and not from its BMC as desired in the proposal.

The template should have something like this:

{% set bmc_name =  hostvars[host]['bmc'].name %}
{% set bmc_data =  (hostvars[bmc_name].ep_host_authentication | selectattr('protocol','match', 'IPMI' ) | list)  %}

This will use ep_host_authentication from the BMC. I will work on this today to try and have a complete solution with your fallback mechanism.

**Comment by ginomcevoy** [comment]
@johnnykeats  What do you think about this?

```
{% for host in (range | sort) %}
  {% if hostvars[host]['ep_equipment_type'] == "server" %}
    {% if hostvars[host]['bmc'] is defined and hostvars[host]['bmc']['name'] is defined %}
      {# Gather BMC network settings #}
      {% set bmc_name = hostvars[host]['bmc'].name %}
      {% if bmc_name in hostvars %}{# BMC is defined outside host #}
        {% set host_bmc = hostvars[bmc_name]['network_interfaces'][0] %}
      {% else %}{# Fall back to BMC in host #}
        {% set host_bmc = hostvars[host]['bmc'] %}
      {% endif %}
      {# Gather BMC credentials settings #}
      {% if hostvars[bmc_name]['ep_host_authentication'] is defined %}{# Check if host_authentication is defined #}
        {% set host_bmc_user = (hostvars[bmc_name]['ep_host_authentication'] | selectattr('protocol','match','IPMI') | map(attribute='user') | list | first) %}
        {% set host_bmc_password = (hostvars[bmc_name]['ep_host_authentication'] | selectattr('protocol','match','IPMI') | map(attribute='password') | list | first) %}
      {% else %}{# Fall back to equipment_authentication | DATAMODEL 2.0 DEPRECATION #}
        {% set host_bmc_user = hostvars[host]['ep_equipment_authentication']['user'] %}
        {% set host_bmc_password = hostvars[host]['ep_equipment_authentication']['password'] %}
      {% endif %}
console name="{{ host }}" dev="ipmitool.exp {{ host_bmc['ip4'] }} {{ host_bmc_user }} {{ host_bmc_password }}"
    {% endif %}
  {% endif %}
{% endfor %}
```

It is meant to work with this additional inventory file:

```
mg_infra:
  children:
    equipment_mc:
      hosts:
        bmanagement1:
          network_interfaces:
            - name: bmanagement1
              ip4: 10.31.111.1
              mac: "08:00:27:dc:f8:f6"
              network: ice1-1
          ep_host_authentication:
            - protocol: IPMI
              user: bmcuser
              password: bmcpass
```

When I test conman, I get the desired behavior, for management1 I get the details from the new file, and for other nodes the role falls back to the information available in each node:

```
console name="management1" dev="ipmitool.exp 10.31.111.1 bmcuser bmcpass"
console name="management2" dev="ipmitool.exp 10.31.100.2 ADMIN ADMI
```

**Comment by johnnykeats** [comment]
You are right.
Fixing template.

**Comment by johnnykeats** [comment]
Can you check now?

**Review by ginomcevoy — DISMISSED** [review]

**Comment by ginomcevoy** [comment]
Hello @johnnykeats , this works fine, thanks!
I tried using the test "if bmc_name in hostvars" because I thought it would be necessary for our requirement. But now I think your solution should work without issues. I am approving the PR 👍

**Comment by johnnykeats** [comment]
Perfect, thank you.
Will update other files asap.

**Comment by johnnykeats** [comment]
@ginomcevoy Please check if the whole PR match your needs.

**Comment by ginomcevoy** [comment]
Hello @johnnykeats sorry I was busy with other pending tasks.
This looks like a good attempt but I am not sure it will be enough. When I looked at the powerman role and I knew it would be harder to implement than conman because the data is grouped and the credentials of the first node is reused for all nodes in a given ansible group. So this solution is incomplete when two nodes in the same group have different credentials in their BMCs.

I will try to come up with an improved approach that gathers BMCs with the same credentials within a group using 
 a dictionary to accumulate nodes using user+pass as a key, and then output a line per dictionary entry. That should produce the desired result, hopefully I will have this tomorrow.

**Comment by ginomcevoy** [comment]
I have made an implementation that I believe achieves the effect, here is the critical part:

```
{% for equipment in j2_equipment_groups_list %}
  {% set hosts = [] %}
  {% set bmcs = [] %}
  {# Structure to group hosts by their BMC credentials: user -> pass -> hosts nested dict #}
  {% set credentials_dict = {} %}
  {% for host in groups[equipment] %}
    {% if host in range and hostvars[host]['bmc']['name'] is defined %}
      {# Gather BMC network settings for current host #}
      {% if hostvars[host]['bmc']['ip4'] is defined %}{# BMC is defined inside host #}
        {% set credentials_host = host %}{# Define host as credentials source #}
      {% else %}{# BMC is defined outside host #}
        {% set credentials_host = hostvars[host]['bmc']['name'] %}{# Define external bmc as credentials source #}
      {% endif %}
      {# Gather BMC credentials settings #}
      {% if hostvars[credentials_host]['ep_host_authentication'] is defined %}{# Check if host_authentication is defined #}
        {% set host_bmc_user = (hostvars[credentials_host]['ep_host_authentication'] | selectattr('protocol','match','IPMI') | map(attribute='user') | list | first) %}
        {% set host_bmc_password = (hostvars[credentials_host]['ep_host_authentication'] | selectattr('protocol','match','IPMI') | map(attribute='password') | list | first) %}
      {% else %}{# Fall back to equipment_authentication | DATAMODEL 2.0 DEPRECATION #}
        {% set host_bmc_user = hostvars[credentials_host]['ep_equipment_authentication']['user'] %}
        {% set host_bmc_password = hostvars[credentials_host]['ep_equipment_authentication']['password'] %}
      {% endif %}
      {# Check if this set of credentials have been used before in a previous host #}
      {% if host_bmc_user not in credentials_dict %}
        {# new user credential, create a dictionary entry for it #}
        {{ credentials_dict.update({host_bmc_user: {}}) }}
      {% endif %}
      {% if host_bmc_password not in credentials_dict[host_bmc_user] %}
        {# new password credential, create an inner dictionary entry for it #}
        {{ credentials_dict[host_bmc_user].update({host_bmc_password: []}) }}
      {% endif %}
      {# Add this host to the list of hosts with the same credentials #}
      {{ credentials_dict[host_bmc_user][host_bmc_password].append(host) }}
    {% endif %}
  {% endfor %}
  {# Render entries for each group of nodes with the same credentials #}
  {% for host_bmc_user in credentials_dict %}
    {% set outer_loop = loop %}
    {% for host_bmc_password in credentials_dict[host_bmc_user] %}
      {% set hosts = credentials_dict[host_bmc_user][host_bmc_password] %}
      {% set bmcs = [] %}
      {% for host in hosts %}
        {{ bmcs.append(hostvars[host]['bmc']['name']) }}
      {% endfor %}
      {# Name device for each set of credentials: first device has equipment name, next ones are indexed #}
      {% if (outer_loop.index*loop.index) > 1 %}
        {% set device_suffix = (outer_loop.index*loop.index) | string %}
      {% else %}
        {% set device_suffix = '' %}
      {% endif %}
device "{{ equipment }}{{ device_suffix }}" "ipmipower" "/usr/sbin/ipmipower --wait-until-on --wait-until-off -h {{ bmcs|nodeset }} -u {{ host_bmc_user }} -p {{ host_bmc_password }} |&"
node "{{ hosts|nodeset }}" "{{ equipment }}{{ device_suffix }}" "{{ bmcs|nodeset }}"
    {% endfor %}
  {% endfor %}
{% endfor %}
```

The idea is to create "sets" of nodes so that the same user/pass credentials are used within each set.
The code is kind of ugly because of the nested dictionaries, and it may also be slow, ideas to improve are welcome of course. 

I tested this with an example with 3 management nodes, and the BMC of management2 has the new data structure and has different credentials. Here is the result, notice that management1 and management3 are correctly grouped together:

```
device "equipment_typeM" "ipmipower" "/usr/sbin/ipmipower --wait-until-on --wait-until-off -h bmanagement[1,3] -u ADMIN -p ADMIN |&"
node "management[1,3]" "equipment_typeM" "bmanagement[1,3]"

device "equipment_typeM2" "ipmipower" "/usr/sbin/ipmipower --wait-until-on --wait-until-off -h bmanagement2 -u bmcuser -p bmcpass |&"
node "management2" "equipment_typeM2" "bmanagement2"
```

I don't understand much of powerman internals but I figured we would need a different device for each set of nodes, so here I used an index to count the sets within each equipment. The first set does not get the index in the name, so this will fall back to the original behavior for one set per equipment.

I don't know how to remove the empty lines though, Jinja is mean when it comes to handling spaces :)

**Comment by ginomcevoy** [comment]
The previous code had a problem, I was not labeling the sets of credentials correctly so there would have been duplicates.
I think this will correctly count each set and label each set in order (<equipment>, <equipment>2, <equipment>3, ...):

```
  {# Render entries for each set of nodes with the same credentials #}
  {# The credentials_count variable is used to keep track of the set count within each equipment #}
  {% set credentials_count = [] %}
  {% for host_bmc_user in credentials_dict %}
    {% for host_bmc_password in credentials_dict[host_bmc_user] %}
      {% set hosts = credentials_dict[host_bmc_user][host_bmc_password] %}
      {% set bmcs = [] %}
      {# Increase the count of sets in this equipment #}
      {{ credentials_count.append(1) }}
      {% for host in hosts %}
        {{ bmcs.append(hostvars[host]['bmc']['name']) }}
      {% endfor %}
      {# Name device for each set of credentials: first device has equipment name, next ones are indexed #}
      {% if credentials_count | length > 1 %}
        {% set device_suffix = credentials_count | length | string %}
      {% else %}
        {% set device_suffix = '' %}
      {% endif %}
device "{{ equipment }}{{ device_suffix }}" "ipmipower" "/usr/sbin/ipmipower --wait-until-on --wait-until-off -h {{ bmcs|nodeset }} -u {{ host_bmc_user }} -p {{ host_bmc_password }} |&"
node "{{ hosts|nodeset }}" "{{ equipment }}{{ device_suffix }}" "{{ bmcs|nodeset }}"
    {% endfor %}
  {% endfor %}
```

**Comment by oxedions** [comment]
My 2 cents : would it be an issue if we create one line per host ? It would make the code much simpler, and if powerman can handle that, then we do not really care of the size of the output configuration file...

**Comment by ginomcevoy** [comment]
Hello @oxedions I agree that the code would be a lot simpler. But I don't know enough about powerman to say if this would be good for the service or not.

**Comment by johnnykeats** [comment]
Would worth a check with a huge inventory. Will do that asap.

**Comment by johnnykeats** [comment]
Answer is no. Powerman cannot handle a lot of different hosts profile.

**Comment by johnnykeats** [comment]
Used your code, and improved it (prevented empty lines spawning).
Created a co-authored commit.
Beware, powerman does not handle a lot of entries: if you define many hosts in the inventory with dedicated credentials for each of them, even with this template, powerman will memory explode.

**Comment by johnnykeats** [comment]
@ginomcevoy Please confirm it fit your needs. Code is ready.

**Review by oxedions — APPROVED** [review]
Took me time to read everything, but ok for me 😊

**Comment by oxedions** [comment]
I will merge this one. This code seems to solve issues.

**Pull request merged**
