### PR TITLE
Fix for issue 534

### PR DESCRIPTION
**Pull request by neilmunday**
Potential fix for issue #534.

Maintains backwards compatibility for CentOS 8.3 and below as well as forwards compatibility for CentOS 8.4 onwards.

### CODE REVIEW

**Comment by oxedions** [comment]
Dear @neilmunday 

I think we can assume that users will now be up to date. So you can create a single file for CentOS_8.
Also, since CentOS is near to deprecation and end of story, I think this is more than enough. 😊

**Comment by neilmunday** [comment]
@oxedions done. Hopefully this will pass the tests now.

**Comment by johnnykeats** [comment]
Will test this code into a dedicated container to validate it.

**Comment by johnnykeats** [comment]
Tested and confirm it works with this fix. This PR is ok for me, and the molecule test broken.
Mostly container image not up to date.

**Comment by neilmunday** [comment]
@johnnykeats CHANGELOG updated though conflicts with the master branch version will need fixing.

**Comment by oxedions** [comment]
Merging. Thanks a lot @neilmunday  for this fix 😊

**Pull request merged**
