### PR TITLE
Fix: ssh_master ssh_slave - rename

### PR DESCRIPTION
**Pull request by oxedions**
As discussed in https://github.com/bluebanquise/bluebanquise/issues/625

### CODE REVIEW

**Comment by oxedions** [comment]
Forgot molecule tests update, converting to draft.

**Comment by neilmunday** [comment]
Looks good to me.

**Review by neilmunday — APPROVED** [review]
Looks good to me.

**Comment by oxedions** [comment]
Thanks !

Merging 😊

**Pull request merged**
