### PR TITLE
fix: check OS info from facts instead of inventory

### PR DESCRIPTION
**Pull request by actatux**

### CODE REVIEW

**Comment by actatux** [comment]
https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html#ansible-fact-namespacing

**Comment by actatux** [comment]
Another method would be to define a default `execpath` in `vars/main.yml` and a specific one in `vars/RedHat_8.yaml`. (similar to #173)

**Comment by actatux** [comment]
Example:
```diff
$ git diff --cached
diff --git a/roles/core/conman/templates/conman.conf.j2 b/roles/core/conman/templates/conman.conf.j2
index fe54f07..6b6bc84 100644
--- a/roles/core/conman/templates/conman.conf.j2
+++ b/roles/core/conman/templates/conman.conf.j2
@@ -1,11 +1,7 @@
 #### Blue Banquise file ####
 ## {{ansible_managed}}
 
-{% if (equipment_profile['operating_system']['distribution'] | lower) in ['redhat', 'centos'] and equipment_profile['operating_system']['distribution_major_version'] < 8 %}
-SERVER execpath="/usr/share/conman/exec"
-{% else %}
-SERVER execpath="/usr/lib/conman/exec"
-{% endif %}
+SERVER execpath="{{ execpath }}"
 SERVER syslog="daemon"
 SERVER logdir="/var/log/conman"
 GLOBAL log="/var/log/conman/%N.log"
diff --git a/roles/core/conman/vars/RedHat_7.yml b/roles/core/conman/vars/RedHat_7.yml
new file mode 100644
index 0000000..1ecca16
--- /dev/null
+++ b/roles/core/conman/vars/RedHat_7.yml
@@ -0,0 +1 @@
+execpath: "/usr/share/conman/exec"
diff --git a/roles/core/conman/vars/main.yml b/roles/core/conman/vars/main.yml
index 193e084..9958a30 100644
--- a/roles/core/conman/vars/main.yml
+++ b/roles/core/conman/vars/main.yml
@@ -1 +1,2 @@
 role_version: 1.0.2
+execpath: "/usr/lib/conman/exec"
```
`RedHat_7.yml` being derived from `os_family` + `distribution_major_version` in the task.

**Comment by actatux** [comment]
What about my proposal above? (https://github.com/bluebanquise/bluebanquise/pull/172#issuecomment-612980174)

**Comment by oxedions** [comment]
I find this logic interesting.
If I understand you well, idea is use some kind of default value if no operating system is found, so an generic pattern, and then a specific one if OS is known.
Am I right ?

**Comment by actatux** [comment]
Yes. Ansible first load variables from vars/mail.yml, then the role start with a first task that look to vars/$OS.yml files, which take precedence. This is implemented in #179 for review.

**Comment by oxedions** [comment]
So go for #179  :-)

**Comment by actatux** [comment]
Close in favour of #179

**Pull request closed without merging**
