### PR TITLE
Modifying hosts jinja template to add host aliases.

### PR DESCRIPTION
**Pull request by remyd1**
This PR modifies hosts_file role to allow the cluster admin to add some aliases for external hosts.

### CODE REVIEW

**Comment by oxedions** [comment]
Dear @remyd1 

Thanks a lot for this PR, and my apologies for the delay of my answer.

I like this change. However, since I made some deep changes on this role in V2, I wish to let it hold few weeks if it is ok for you ?
Then we can merge it into V2 directly.

**Comment by remyd1** [comment]
It is Ok. Thanks.

**Comment by oxedions** [comment]
Dear @remyd1 

New role is available now, sorry for the delay.
You can find it at https://github.com/bluebanquise/bluebanquise/tree/master/collections/infrastructure/roles/hosts_file

**Comment by remyd1** [comment]
Hi,

I just checked if it can be merged with new version, but, well, there are too many changes for me to do so.

My PR was a way to manage host names aliases, and I don't see a way to do it in BB 2.0. Is it possible anyway ?

Best,
Rémy

**Comment by remyd1** [comment]
Ok; done. Finally, it was easy but BB 2.0 seems to be a huge change (...) !

**Comment by oxedions** [comment]
Hello @remyd1 ! 😊 
Thanks a lot for these changes. Il will check it asap, probably Monday.
Well, there was some changes, but not that much you will see. I mainly focused on stability,  and I avoided introducing too much breaking changes.

**Comment by remyd1** [comment]
Ok. I stay tune !

**Comment by oxedions** [comment]
Small update: I havent forgotten the review, just some pressure with kids. I will work on it asap 😊

**Comment by oxedions** [comment]
Dear @remyd1 

I checked code, its ok for me 😊 

Merging ! Thanks a lot for this contribution !

**Review by oxedions — APPROVED** [review]

**Comment by remyd1** [comment]
Great 👍

**Pull request merged**
