### PR TITLE
Allow custom iso path, fix global logic, and fix multiple small things

### PR DESCRIPTION
**Pull request by oxedions**
Fix https://github.com/bluebanquise/bluebanquise/issues/962
Merge https://github.com/bluebanquise/bluebanquise/pull/929 into new master
Fix many few things
Start Ubuntu 24.04 support (to be more tested, loki not working)

Note:
* need to remove -u jarvice from squeue
* need to remove hardcoded benoit user

### CODE REVIEW

**Comment by oxedions** [comment]
@vedmonds please check https://github.com/bluebanquise/bluebanquise/pull/963/commits/685dbfbad05fa7062185145ca9cec6bc02e13cee
@jpm38 please check https://github.com/bluebanquise/bluebanquise/pull/963/commits/06c77f4163db5e114c539bdfb64ce3eec901a2ec

**Comment by vedmonds** [comment]
Thank you!

**Comment by jpm38** [comment]
Sounds good to me ! thanks a lot

**Comment by oxedions** [comment]
Thanks you @vedmonds  @jpm38  for checking !

Merging. Please note that since pxe was modified, I will run deeper tests to make sure everything is still ok.

**Pull request merged**
