### PR TITLE
fix handlers tags + service tasks rework

### PR DESCRIPTION
**Pull request by bouriquet**

### CODE REVIEW

**Comment by oxedions** [comment]
Dear @bouriquet 

https://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

:-)

Ben

**Comment by actatux** [comment]
Also, this is for `master` so I would remove the `[1.2]` from the PR title. This is not a blocker though.

**Comment by oxedions** [comment]
Dear @actatux , Dear @bouriquet 

Yes, please remove these 3 files, so I can merge it asap :-)

Many thanks

Ben

**Comment by actatux** [comment]
I don't know how I could amend an existing PR from someone else in GitHub. (would be easy with Gerrit :) )

Please merge #127 first, I expect it to fix the conflict reported by GitHub here.

**Pull request merged**
