### PR TITLE
fix: gather OS vars in pxe_stack

### PR DESCRIPTION
**Pull request by actatux**
Search vars in:
 - `<distribution>_<major>.yml`    # eg. CentOS_8.yml
 - `<os_family>_<major>.yml`      # eg. RedHat_8.yml
 - `<distribution>.yml`            # eg. CentOS.yml
 - `<os_family>.yml`               # eg. RedHat.yml

Prefix role variables with the role name.

Port code to Ansible fact namespacing: ansible_* -> ansible_facts.*

See #205

### CODE REVIEW

**Comment by actatux** [comment]
Draft PR to discuss the implementation before final reviews.

**Comment by oxedions** [comment]
Hello @actatux 

On my side, after having a look on the diff from this PR, I think this is the good way to go.

Code is simple to read, variable loading mechanism is logic, and done at beginning. Ansible facts are now all under ansible_facts.

Since it is a draft, I didn't checked syntax deeper, but 100% ok with logic 😃

**Comment by oxedions** [comment]
I need this one. Merging.

**Comment by oxedions** [comment]
FI, Cherry-picked it.

**Pull request merged**
