### PR TITLE
ci: run Molecule test with GitHub actions

### PR DESCRIPTION
**Pull request by actatux**
- distro:
   - centos7
   - centos8
- role:
   - core/display_tuning
   - core/dns_client
   - core/dns_server
   - core/time
   - addons/clustershell
   - addons/users_basic

### CODE REVIEW

**Comment by oxedions** [comment]
I do not know Molecule, so I trust you on this.

Idea is to run deeper tests on the role, or even test deployment of them ?
If deployment, can we dot that with our free Github account ?

**Comment by strus38** [comment]
Should we add also: [slack-notifier](https://github.com/marketplace/actions/slack-notify)?

**Comment by actatux** [comment]
> Idea is to run deeper tests on the role, or even test deployment of them ?

This change runs unit tests on the roles, when Molecule is implemented. Each role will be tested independently from the others.

> If deployment, can we dot that with our free Github account ?

No deployment yet. I believe this is not possible with GitHub free.

> Should we add also: slack-notifier?

To notify results of GH actions? Might be a good idea, maybe in a dedicated channel?

**Comment by oxedions** [comment]
Is there a way to configure molecule for the whole stack in one place ? To avoid many files in each roles, since roles are not designed to be used externally of the stack.

**Comment by actatux** [comment]
No. Unit test of roles need to be unitary. It helps to detect issues like #169.
We need to do integration tests for the stack, but this is a different topic.

Note that with current implementation, any PR to a single role will trigger a molecule test for all roles.

**Comment by oxedions** [comment]
Ok thanks.

We will need to ensure these files are removed from releases rpm :-)

**Comment by actatux** [comment]
Indeed, nice catch! #176 for tracking.

**Comment by actatux** [comment]
See the "**All checks have passed**" below. :-)

**Pull request merged**
