### PR TITLE
Feat: pam_limits role creation

### PR DESCRIPTION
**Pull request by johnnykeats**
Need ulimits to restrict nasty users on login nodes.
(mpirun -n 1024 .....)

### CODE REVIEW

**Review by oxedions — DISMISSED** [review]
Ok for me 😊

**Review by neilmunday — DISMISSED** [review]
Looks good to me.

**Comment by neilmunday** [comment]
Do we need any molecule tests for this?

**Comment by johnnykeats** [comment]
Let me try that.

**Comment by johnnykeats** [comment]
@neilmunday  Now there are molecule tests.

**Review by oxedions — APPROVED** [review]

**Review by neilmunday — COMMENTED** [review]
Looks ok to me

**Pull request merged**
