### PR TITLE
Oxedions/dev/1.5 core

### PR DESCRIPTION
**Pull request by oxedions**
Next 1.5 release core modifications.

1.5 is a step release before integrating other distributions like OpenSuse, Ubuntu, etc. Small steps are better than big ones.

I did these modifications in an outside branch to not break the master before finishing the main part.
Next devs will be done in later PR, but they are small, this is the major one.

* Updated Readme
* New datamodel
* Removed community roles
* Add j2 variable for roles
* Adapt automatic tests

Missing, to be done in later PRs:

* Still need to remove nic and display_tuning roles.
* Also need to update main README to reflect that 1.5 will not integrate non RHEL derivated OS.
* Update documentation.
* Move tools to tools repository to install them via rpm (bootset, disklessset)

To read this preview, do not read the whole diff.

Read key PR, others are either clones or small diff.
* https://github.com/bluebanquise/bluebanquise/pull/536/commits/b1fc4fffff2181b00ec4885eb2892e6e47815142
* https://github.com/bluebanquise/bluebanquise/pull/536/commits/64cf589de6ba7d0ecfee68b2d6ee51a5c530e734
* https://github.com/bluebanquise/bluebanquise/pull/536/commits/3a06586c319da15f77df48fc02f0a29abf42fd61
* https://github.com/bluebanquise/bluebanquise/pull/536/commits/330fe15ce9d179340b25e471dc6d5aa44c7791eb

### CODE REVIEW

**Comment by oxedions** [comment]
Updated

**Review by bouriquet — APPROVED** [review]

**Comment by oxedions** [comment]
@johnnykeats Could you have a look on this PR ?

**Comment by johnnykeats** [comment]
PR is ok.

The mechanism allows merging both old (vars tree) and new (include vars) methods. Don't see any issues.

Few comments:

* Why dropping ability to have generic values? This was available with include_vars, you should add a last level in your j2 code (generic).
* pxe_stack role has an issue on template, please check.
* You should insist more in the README on difference between Core and Community roles. Core = deploy OS + vital infrastructure services. Community = production services.

**Comment by oxedions** [comment]
>     * Why dropping ability to have generic values? This was available with include_vars, you should add a last level in your j2 code (generic).

You mean values that were in the vars/main.yml ?

>     * pxe_stack role has an issue on template, please check.

Yes, I forgot to commit the file. You can check it was corrected on Tumulus.

>     * You should insist more in the README on difference between Core and Community roles. Core = deploy OS + vital infrastructure services. Community = production services.

Ok !

**Pull request merged**
