### PR TITLE
Feat: Adding advanced repositories path handling

### PR DESCRIPTION
**Pull request by oxedions**

### CODE REVIEW

**Comment by johnnykeats** [comment]
Yo Ox.
What are you trying to achieve?

**Comment by oxedions** [comment]
Hey !
Out of the cave ? The stack is missing its main architect.

I am trying to add possibility to handle minor or major versions, and also dynamic path on client side. See https://github.com/bluebanquise/bluebanquise/pull/149/files

**Comment by johnnykeats** [comment]
Yes. Back online.
Reading all what was done. Please add me in owners and in team.

**Comment by johnnykeats** [comment]
Too much complexity was added in the core. Some roles must move to advanced_core.
Are you aware merge may be dropped?

**Comment by oxedions** [comment]
Yes, I am aware. I opened a case at RHEL, in case of...

Glad to read you are back ! After all, this stack is also your baby.

Let me do that.

Regarding complexity, you are the architect, so feel free to investigate.
Let's have a direct talk.

**Comment by johnnykeats** [comment]
Frozen. Need time to investigate all of this.

**Pull request closed without merging**
