### PR TITLE
Feat: nfs_client - Change sebooleans input variables

### PR DESCRIPTION
**Pull request by oxedions**
Fix issue https://github.com/bluebanquise/bluebanquise/issues/567 by adding a new variable able to handle multiple sebooleans.

### CODE REVIEW

**Comment by oxedions** [comment]
Ready. @johnnykeats  please have a look.

**Comment by johnnykeats** [comment]
Would be nice to provide backward compatibility, using `default` maybe?
Prevents bc.

**Comment by oxedions** [comment]
Ok, I will have a look.

**Comment by johnnykeats** [comment]
This does not really introduce a bc, as default already comply with previous default value.
This is a change, not a breaking change. You can merge it this way to me.

**Review by johnnykeats — APPROVED** [review]

**Comment by oxedions** [comment]
Ok. I will review the whole example inventories anyway.

**Pull request merged**
