### PR TITLE
Doc: Diskless - Improve the readme

### PR DESCRIPTION
**Pull request by oxedions**
Refer to #420 

This tags allows the pre_task to always run, whatever the tags used, since it is only internal mechanism and mandatory for other roles to run properly in the diskless chroot.

### CODE REVIEW

**Review by btravouillon — APPROVED** [review]
Looks good to me. 👍

**Comment by oxedions** [comment]
SO you took the opportunity to add what was discussed in #420.
Ok for me. @hmeAtos ?

**Comment by btravouillon** [comment]
> SO you took the opportunity to add what was discussed in #420.

and #374.

**Review by btravouillon — APPROVED** [review]
Looks good to me. 👍

**Comment by oxedions** [comment]
Ok cool !

Perfect, merging.

**Comment by hmeAtos** [comment]
> SO you took the opportunity to add what was discussed in #420.
> Ok for me. @hmeAtos ?

Yes good for me
Thanks

**Pull request merged**
