### PR TITLE
bug fix: missing setting of current_hostvars

### PR DESCRIPTION
**Pull request by jpm38**
Fix a missing setting of current_hostvars variable.

### CODE REVIEW

**Review by btravouillon — DISMISSED** [review]
Looks good to me. 👍
Hopefully there won't be any other bug introduced with merge of #470 with 0 positive review... 😞

**Comment by johnnykeats** [comment]
Strange code, makes no sense. Maybe bad too large **replace**.

Please update code from (only this loop):

```
    {% set current_hostvars = hostvars[host] %}{# buffer #}
    {% if current_hostvars['iceberg_master'] == j2_current_iceberg %}
```

To

```
    {% if hostvars[host]['iceberg_master'] == j2_current_iceberg %}
```

No need for buffer here.

**Review by johnnykeats — CHANGES_REQUESTED** [review]
Strange code, makes no sense. Maybe bad too large **replace**.

Please update code from (only this loop):

```
    {% set current_hostvars = hostvars[host] %}{# buffer #}
    {% if current_hostvars['iceberg_master'] == j2_current_iceberg %}
```

To

```
    {% if hostvars[host]['iceberg_master'] == j2_current_iceberg %}
```

No need for buffer here.

**Review by btravouillon — APPROVED** [review]
Looks good to me. 👍

**Review by johnnykeats — APPROVED** [review]
OK !

**Pull request merged**
